/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false worker/worker-configuration.d.ts` (hash: 468f2d19beb97f8cf33255846efca5a1)
interface __BaseEnv_Env {
	RATE_LIMITER: RateLimit;
	DYNAMIC_ENVIRONMENT_ID: "3608a494-ff5c-4cbc-a425-ddc382e4a90a";
	ALLOWED_ORIGINS: "https://bryfeng.github.io,http://127.0.0.1:4318,http://localhost:4318";
	DYNAMIC_API_TOKEN: string;
	LAB_ACCESS_KEY: string;
	LAB_SESSIONS: DurableObjectNamespace<import("./index").FlowLabSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "FlowLabSession";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DYNAMIC_ENVIRONMENT_ID" | "ALLOWED_ORIGINS" | "DYNAMIC_API_TOKEN" | "LAB_ACCESS_KEY">> {}
}
