// Static editorial examples. This file never invokes ONE, Dynamic, or a chain.
const merchantId = 'DEMO-MERCHANT-001';
const businessAccountId = 'DEMO-BUSINESS-001';
const providerWalletId = 'DEMO-DYNAMIC-WALLET-001';
const walletId = 'DEMO-WALLET-001';
const settlementProfileId = 'DEMO-PROFILE-001';
const intentId = 'DEMO-INTENT-1042';
const attemptId = 'DEMO-ATTEMPT-1042';
const flowId = 'DEMO-FLOW-1042';
const batchId = 'DEMO-BATCH-001';
const env = '<DYNAMIC_ENVIRONMENT_ID>';
const merchantAddress = '<MERCHANT_EVM_ADDRESS>';
const payerAddress = '<PAYER_EVM_ADDRESS>';
const tokenAddress = '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
const asset = { chainName: 'EVM', chainId: '8453', tokenAddress, symbol: 'USDC', tokenDecimals: 6 };
const flowPath = `/sdk/${env}/flow/${flowId}`;
const batchPath = `/api/v1/crypto-payouts/batches/${batchId}`;
const session = { 'X-Dynamic-Flow-Session-Token': '<FLOW_SESSION_TOKEN>' };
const auth = key => ({ Authorization: 'Bearer <ONE_AUTH_TOKEN>', ...(key ? {'Idempotency-Key':key} : {}) });
const sources = {
  account: {label:'Dynamic · Create a business account',url:'https://www.dynamic.xyz/docs/javascript/reference/business-accounts/create-a-business-account'},
  wallet: {label:'Dynamic · Add wallets',url:'https://www.dynamic.xyz/docs/javascript/reference/business-accounts/add-wallets'},
  signing: {label:'Dynamic · Business wallet signing',url:'https://www.dynamic.xyz/docs/javascript/reference/business-accounts/signing'},
  flow: {label:'Dynamic · Fireblocks Flow API',url:'https://www.dynamic.xyz/docs/overview/fireblocks-flow-api'}
};
const call = (kind, operation, actor, request, response, notes, source, headers) => ({kind, operation, actor, request, response, notes, source, headers});
const one = (op, req, res, note, key) => call('Proposed ONE contract',op,'ONE backend',req,res,note,null,auth(key));
const provider = (op, actor, req, res, note, source, headers) => call('Documented provider method',op,actor,req,res,note,source,headers);
const internal = (op, req, res, note) => call('Illustrative internal handoff',op,'Proposed ONE service responsibility',req,res,note);
const items = [
  {itemId:'DEMO-ITEM-001',merchantReference:'SUPPLIER-104',toAddress:'<SUPPLIER_A_EVM_ADDRESS>',amount:'400.00'},
  {itemId:'DEMO-ITEM-002',merchantReference:'SUPPLIER-105',toAddress:'<SUPPLIER_B_EVM_ADDRESS>',amount:'250.00'},
  {itemId:'DEMO-ITEM-003',merchantReference:'SUPPLIER-106',toAddress:'<SUPPLIER_C_EVM_ADDRESS>',amount:'150.00'}
];
const transferPlans = items.map((item,i) => ({itemId:item.itemId,attemptId:`DEMO-PAYOUT-ATTEMPT-00${i+1}`,walletId,chainId:asset.chainId,contract:tokenAddress,function:'transfer(address,uint256)',recipient:item.toAddress,amountBaseUnits:['400000000','250000000','150000000'][i]}));
export default {
  title:'Later extension: business wallets and payouts',
  date:'23 September 2026',
  subtitle:'An extended scenario after Flow checkout is established.',
  intro:'This separate example follows a merchant who adds a shared business wallet, then reuses Flow collection and explores a later crypto payout batch.',
  premise:'The merchant creates a shared USDC wallet, receives 1,000 USDC through Flow, then pays three suppliers a total of 800 USDC.',
  scope:'This later-stage static example is separate from the SPARK Flow-first demo. It uses proposed service contracts and fictional outcomes for the development team and their LLM.',
  assumptions:[
    ['Example only','DEMO-* identifiers and <ANGLE_BRACKET> values are fictional placeholders, so the requests illustrate the contract without providing runnable payloads.'],
    ['Provider access','Dynamic Business Accounts require early access, and Flow requires enterprise enablement; neither feature is assumed enabled in ONE’s environment.'],
    ['Wallet authority','The authenticated merchant representative owns the Dynamic business account and becomes its first wallet signer in this example.'],
    ['Asset and fees','All crypto movements use USDC on Base, with six decimals; sufficient native ETH for gas is assumed funded separately.'],
    ['Invoice and receipt','The invoice is denominated in USD, while the quote and observed receipt specify USDC; the sample amounts do not establish a guaranteed exchange rate.'],
    ['Scope','Auto-conversion remains on hold, and this example creates no fiat credit or transfer from ONE’s custody balances.']
  ],
  bindings:[
    ['Merchant',merchantId,'ONE authentication context','Authorises wallet registration, payment intents and batches'],
    ['Business account',businessAccountId,'Dynamic account creation · 1.1','Owns the provider wallet; verified at registration'],
    ['Provider wallet',providerWalletId,'Dynamic wallet creation · 1.2','Selected by exact ID when the merchant signs'],
    ['ONE wallet',walletId,'ONE wallet registration · 1.3','Settlement profile and batch funding source'],
    ['Merchant address',merchantAddress,'Verified provider wallet address · 1.3','Flow destination and batch sender'],
    ['Settlement profile',settlementProfileId,'Gateway profile · 1.4','Locked into the payment intent'],
    ['Payment intent',intentId,'Gateway intent · 2.1','Order DEMO-ORDER-1042 and collection receipt'],
    ['ONE attempt',attemptId,'Gateway attempt · 2.1','Links the intent to one provider flow'],
    ['Provider flow',flowId,'Flow creation · 2.1','Source, quote, prepare, broadcast and settlement'],
    ['Batch',batchId,'Crypto payout service · 3.1','Three separate supplier payments and their outcomes']
  ],
  sections:[
    {id:'business-wallet',number:'01',title:'Business wallet setup',outcome:'One registered wallet',description:'The merchant creates a business wallet once, and ONE makes that wallet available to collection and payout services.',services:'Merchant workspace → Account / wallet services → Dynamic',steps:[
      {id:'1.1',title:'Create the business account',experience:'The merchant chooses “Create business wallet” and names the account used by their team.',service:'ONE supplies the authenticated merchant context; Dynamic creates the business account for the signed-in representative.',carry:'Carry DEMO-BUSINESS-001 into wallet creation, with DEMO-MERCHANT-001 retained as the ONE tenant reference.',calls:[
        provider('createBusinessAccount({...})','Merchant client · authenticated Dynamic user',{name:'Example Merchant Treasury',externalRef:merchantId},{id:businessAccountId},'Response excerpt: account.id is the documented account identifier, while externalRef is a non-unique label that cannot prove ownership.','account')
      ]},
      {id:'1.2',title:'Add the wallet',experience:'The merchant receives an EVM wallet owned by the business account, with the representative as its first signer.',service:'Dynamic provisions the wallet; ONE will register its verified account relationship separately in the next step.',carry:'Carry the business account, provider wallet ID and verified address together when registering the wallet with ONE.',calls:[
        provider('createWalletForBusinessAccount({...})','Merchant client · authenticated account owner',{businessAccountId,chain:'EVM'},{providerWalletId,businessAccountId,address:merchantAddress,chainFamily:'EVM'},'Normalised example output, not a verbatim provider response schema; map these values from the actual SDK result and account readback. EVM selects a chain family, while Base network selection happens in the settlement profile.','wallet')
      ]},
      {id:'1.3',title:'Register the wallet with ONE',experience:'The wallet appears under the merchant’s accounts and becomes available across ONE’s collection and payout experiences.',service:'ONE account / wallet services verify the merchant-to-provider relationship, then store the wallet reference and its verified address.',carry:'Gateway and payouts now reference DEMO-WALLET-001; neither service creates a separate merchant wallet or trusts an arbitrary address.',calls:[
        one('POST /api/v1/crypto-wallets',{provider:'dynamic',businessAccountId,providerWalletId,label:'Operating wallet'},{id:walletId,merchantId,provider:'dynamic',businessAccountId,providerWalletId,addresses:[{chainName:'EVM',address:merchantAddress}],status:'verified'},'Derive the merchant and environment from ONE authentication and configuration, then verify membership, wallet ownership and authorised registration through trusted provider evidence. The verification mechanism still needs agreement; client-submitted IDs or externalRef alone are insufficient.','wallet-register-001')
      ]},
      {id:'1.4',title:'Choose how the wallet receives payments',experience:'The merchant chooses USDC on Base as the destination for this checkout’s collections.',service:'Gateway creates an immutable settlement profile using the shared wallet resource and ONE’s supported asset configuration.',carry:'Carry DEMO-PROFILE-001 into checkout creation, with its wallet, address and asset settings locked into each payment intent.',calls:[
        one('POST /gateway/v3/settlement-profiles',{walletId,chainId:asset.chainId,tokenAddress},{id:settlementProfileId,walletId,asset,destinationAddress:merchantAddress,version:1},'ONE resolves the address and token metadata server-side, verifies support, and preserves existing payment snapshots when a new profile replaces this one.','profile-create-001')
      ]}
    ]},
    {id:'fireblocks-flow',number:'02',title:'Fireblocks Flow collection',outcome:'1,000 USDC received',description:'The customer pays a USD invoice through Flow, and ONE records the crypto delivered to the business wallet.',services:'Checkout → Gateway / orchestration → Flow → Reconciliation',steps:[
      {id:'2.1',title:'Create the payment and its Flow attempt',experience:'The merchant creates a 1,000 USD payment request, and the customer opens checkout to choose a funding wallet.',service:'Gateway locks the order and destination, then its Flow adapter creates one provider attempt from those server-owned terms.',carry:'Link DEMO-ORDER-1042 → DEMO-INTENT-1042 → DEMO-ATTEMPT-1042 → DEMO-FLOW-1042 before returning checkout progress.',calls:[
        one('POST /gateway/v3/payment-intents',{amount:'1000.00',currency:'USD',merchantReference:'DEMO-ORDER-1042',settlementProfileId,expiresInSeconds:900},{id:intentId,status:'requires_payment',settlementProfileId,checkoutUrl:`https://checkout.example.invalid/pay/${intentId}`},'The merchant reference identifies the order; ONE freezes the amount, currency, destination and expiry from the authorised merchant request.','intent-create-1042'),
        call('Proposed ONE contract',`POST /gateway/v3/payment-intents/${intentId}/attempts`,'Checkout → Gateway',{}, {id:attemptId,intentId,provider:'dynamic_flow',providerFlowId:flowId,status:'initiated'},'Authenticate checkout with an intent-scoped capability whose issuance and expiry still need specification; never expose the merchant API token to the payer.',null,{'Authorization':'Bearer <INTENT_SCOPED_CHECKOUT_TOKEN>','Idempotency-Key':'attempt-create-1042'}),
        provider(`POST /server/${env}/flow/payment`,'ONE Flow adapter → Dynamic',{amount:'1000.00',currency:'USD',settlementConfig:{strategy:'cheapest',settlements:[asset]},destinationConfig:{destinations:[{chainName:'EVM',type:'address',identifier:merchantAddress}]},memo:{orderId:'DEMO-ORDER-1042',oneIntentId:intentId,oneAttemptId:attemptId},expiresIn:900,disableSwaps:true},{flow:{id:flowId,amount:'1000.00',currency:'USD',executionState:'initiated',settlementState:'none'}},'Response excerpt with fictional IDs; the provider call happens inside attempt creation before ONE returns its attempt response. Pass the remaining intent lifetime as expiresIn, using 900 here because creation is immediate. Persist the attempt first and reconcile uncertain creation before trying again.','flow',{Authorization:'Bearer <SERVER_TOKEN_WITH_FLOW_WRITE>'})
      ]},
      {id:'2.2',title:'Attach the customer’s wallet and get a quote',experience:'The customer selects their funding wallet and sees the amount they need to send before signing anything.',service:'The payer client attaches its source to Flow, receives a per-flow session capability, and requests a quote for Base USDC.',carry:'Keep the returned session token private to this checkout, and carry the current quote into preparation before its 60-second expiry.',calls:[
        provider(`POST ${flowPath}/source`,'Payer client → Dynamic',{sourceType:'wallet',fromAddress:payerAddress,fromChainId:'8453',fromChainName:'EVM'},{sessionToken:'<FLOW_SESSION_TOKEN>',flow:{id:flowId,executionState:'source_attached'}},'Initial source attachment requires no token and returns the session token once; source screening then runs asynchronously. This source is the customer wallet, not the merchant settlement wallet.','flow'),
        provider(`POST ${flowPath}/quote`,'Payer client → Dynamic',{fromTokenAddress:tokenAddress,slippage:0.005},{id:flowId,executionState:'quoted',quoteVersion:1,quote:{version:1,fromAmount:'1000.00',toAmount:'1000.00'}},'Illustrative quote excerpt: these token amounts are fixture outcomes, not a USD-to-USDC guarantee or fee estimate. Slippage is a decimal tolerance, so 0.005 means 0.5%; this example fixes the same chain and token with swaps disabled.','flow',session)
      ]},
      {id:'2.3',title:'Prepare, sign and report the transaction',experience:'The customer reviews the prepared transaction in their wallet and authorises the payment from their own funds.',service:'Flow checks readiness and builds the signing payload; the customer wallet signs and broadcasts before the client reports its hash.',carry:'Carry <COLLECTION_TX_HASH> from the wallet into Flow’s broadcast notification, while preserving the flow and intent relationship.',calls:[
        provider(`GET ${flowPath}`,'Payer client → Dynamic',null,{id:flowId,riskState:'cleared',executionState:'quoted'},'Response excerpt after screening clears; this unauthenticated provider read does not replace authorisation on ONE’s merchant endpoints.','flow'),
        provider(`POST ${flowPath}/prepare`,'Payer client → Dynamic',{assertBalanceForGasCost:true,assertBalanceForTransferAmount:true},{executionState:'signing',quote:{signingPayload:{chainName:'EVM',chainId:'8453',evmTransaction:{to:tokenAddress,data:'<PROVIDER_GENERATED_CALLDATA>',value:'0x0',gasLimit:'<PROVIDER_GAS_LIMIT>'}}}},'Response excerpt: retain the actual prepared payload, including evmApproval when present, and complete any required approval before the main transaction. An expired quote must be refreshed; prepare does not accept an invented quoteVersion parameter.','flow',session),
        call('Wallet signing handoff','Connected EVM wallet · sign and broadcast','Customer wallet',{sourceAddress:payerAddress,chainId:'8453',payloadFrom:'prepare.quote.signingPayload'},{txHash:'<COLLECTION_TX_HASH>'},'This is a normalised handoff, not a new API method; use the connected wallet’s documented transaction signing and submission support. Show actual transfer and gas costs before signing.','flow'),
        provider(`POST ${flowPath}/broadcast`,'Payer client → Dynamic',{txHash:'<COLLECTION_TX_HASH>'},{executionState:'broadcasted'},'This call reports a transaction already broadcast by the wallet; it does not send funds or prove settlement. After a wallet broadcasts, uncertainty must be reconciled rather than treated as a safe opportunity to cancel or pay again.','flow',session)
      ]},
      {id:'2.4',title:'Confirm delivery to the merchant wallet',experience:'The merchant sees the payment as received once ONE has matched the delivered crypto to the original payment request.',service:'The Flow adapter tracks provider settlement, while reconciliation verifies the destination transfer and records a receipt against the intent.',carry:'The confirmed receipt establishes the example’s 1,000 USDC wallet funding, which the payout service must still recheck before submission.',calls:[
        provider(`GET ${flowPath}`,'ONE reconciliation / payer progress read',null,{id:flowId,executionState:'source_confirmed',settlementState:'completed'},'Response excerpt: source_confirmed alone is insufficient, and ONE must handle failed, cancelled or expired execution plus failed settlement. Polling is documented without authentication; the implementation may use verified webhooks and reconcile current state.','flow'),
        internal('Reconcile destination transfer',{intentId,attemptId,flowId,expectedWalletId:walletId,expectedDestination:merchantAddress,expectedAsset:asset},{receiptId:'DEMO-RECEIPT-1042',walletId,settlementTxHash:'<COLLECTION_TX_HASH>',receivedAmount:'1000.000000',receivedBaseUnits:'1000000000',asset},'Normalised internal record: verify chain, token, recipient, amount and confirmation policy against transaction evidence. The same-chain example uses one transaction hash; routed flows may have different source and settlement hashes.'),
        one(`GET /gateway/v3/payment-intents/${intentId}`,null,{id:intentId,status:'settled',amount:'1000.00',currency:'USD',attemptId,providerFlowId:flowId,receipt:{id:'DEMO-RECEIPT-1042',walletId,asset,amount:'1000.000000',transactionHash:'<COLLECTION_TX_HASH>'}},'A crypto receipt is distinct from a ONE fiat balance; record fees and actual delivered amounts from evidence rather than deriving them from the invoice.')
      ]}
    ]},
    {id:'crypto-batches',number:'03',title:'Crypto batch payouts',outcome:'800 USDC paid · 200 retained',description:'The merchant uses the same wallet to pay three suppliers, with separate authorisation and transaction records for every recipient.',services:'Merchant workspace → Payouts / approvals → Wallet signer → Reconciliation',steps:[
      {id:'3.1',title:'Build and review the batch',experience:'The merchant enters or imports three suppliers, checks their addresses and reviews an 800 USDC total before submitting.',service:'ONE’s payout service stores the batch, validates its recipients and funding route, and associates every item with a stable reference.',carry:'Carry DEMO-BATCH-001 and version 1 into submission, with recipient amounts fixed at 400, 250 and 150 USDC.',calls:[
        one('POST /api/v1/crypto-payouts/batches',{fundingSource:{type:'business_wallet',walletId},asset,merchantReference:'SUPPLIERS-SEPT-001',items:items.map(({itemId,...rest})=>rest)},{id:batchId,version:1,status:'ready_for_review',totalAmount:'800.00',asset,items:items.map(item=>({...item,status:'validated'}))},'The example assumes valid real-format addresses and cleared checks when placeholders are replaced. Validation creates a job without moving funds; retain the reviewed batch version and each recipient reference. Reuse of ONE’s existing dashboard batch service remains a follow-up item.','batch-create-001')
      ]},
      {id:'3.2',title:'Submit the reviewed batch for signing',experience:'The merchant approves the reviewed batch, and the authorised wallet signer receives the three transactions needed to pay it.',service:'Payout orchestration rechecks permissions, policy, chain balance and gas, then records execution attempts and builds each transfer for the wallet signer.',carry:'Keep each item tied to its execution attempt and prepared transfer; ONE approval does not give the backend the merchant’s signing authority.',calls:[
        one(`POST ${batchPath}/submit`,{approvedVersion:1},{id:batchId,status:'awaiting_signature',fundingSource:{type:'business_wallet',walletId},submissionId:'DEMO-SUBMISSION-001',signingRequests:transferPlans.map(plan=>({itemId:plan.itemId,attemptId:plan.attemptId,signingRequestId:`SIGN-${plan.itemId}`}))},'Reject a stale approvedVersion, require an active authorised signer, and use the reviewed recipient set. The signer handoff and payload transport still need specification; these reference IDs describe the required association.','batch-submit-001'),
        internal('Observe funds and prepare three ERC-20 transfers',{walletId,address:merchantAddress,asset,requestedAmount:'800.00'},{observedWalletBalance:'1000.000000',reservedByThisBatch:'800.000000',unreservedByOne:'200.000000',nativeGasFunding:'assumed_sufficient',transfers:transferPlans},'Amounts are decimal strings, and transfer units are integers using six token decimals. ONE’s reservation coordinates its own jobs; a merchant-controlled wallet can still spend outside ONE, so recheck funds and nonce state before signing and reconcile external activity.')
      ]},
      {id:'3.3',title:'Sign each payment and record its broadcast',experience:'The active signer approves the supplier payments, and the dashboard starts tracking each transaction as its own payout.',service:'The client selects the exact Dynamic wallet for DEMO-WALLET-001, signs its prepared transfers, and reports hashes for ONE to reconcile.',carry:'Record each item and attempt alongside its transaction hash, preserving signed transaction identity and nonce when a broadcast result is uncertain.',calls:[
        provider('getWalletAccounts()','Merchant client · active Dynamic signer',null,{selectedProviderWalletId:providerWalletId,selectedAddress:merchantAddress},'Normalised selection excerpt, not a verbatim SDK return; match the registered provider wallet and address rather than selecting the first account. Admin or viewer membership alone does not grant signing authority.','signing'),
        call('Wallet signing handoff','Connected business wallet · sign and broadcast each transfer','Merchant’s active wallet signer',{walletId,providerWalletId,transfers:transferPlans},{transactions:items.map((item,i)=>({itemId:item.itemId,attemptId:transferPlans[i].attemptId,transactionHash:`<PAYOUT_${i+1}_TX_HASH>`}))},'Normalised handoff using standard EVM signing; bind chain, contract, recipient, amount, nonce and signing request to the reviewed batch. No Dynamic-specific batch signing or quorum API is assumed. The final signer-client transport and transaction preparation interfaces remain to be specified.','signing'),
        one(`POST ${batchPath}/items/DEMO-ITEM-001/broadcast`,{attemptId:'DEMO-PAYOUT-ATTEMPT-001',transactionHash:'<PAYOUT_1_TX_HASH>'},{itemId:'DEMO-ITEM-001',status:'broadcasted',amount:'400.00'},'Additional proposed endpoint for this walkthrough: report each item’s transaction using its own attempt ID and idempotency key. Repeat for items 002 and 003 with their matching hashes; a reported hash is only a claim until ONE verifies sender, chain, token, recipient and amount.','payout-broadcast-001')
      ]},
      {id:'3.4',title:'Read the result and keep failures separate',experience:'The merchant sees which suppliers have been paid and can follow up on any outstanding item without repeating completed payments.',service:'Reconciliation confirms each transaction and updates payout records, while the batch service derives its overall status from those individual outcomes.',carry:'The completed example leaves 200 USDC in the wallet after 800 USDC of transfers, with native gas accounted for separately.',calls:[
        one(`GET ${batchPath}`,null,{id:batchId,status:'completed',asset,totalAmount:'800.00',confirmedAmount:'800.00',items:items.map((item,i)=>({...item,status:'confirmed',attemptId:transferPlans[i].attemptId,transactionHash:`<PAYOUT_${i+1}_TX_HASH>`})),walletObservation:{walletId,balance:'200.000000',reservedByThisBatch:'0.000000'}},'Mark completed only after every item reaches the agreed confirmation policy; preserve all transaction evidence and never infer success from batch submission.'),
        internal('Alternative outcome: third broadcast is uncertain',{batchId,uncertainItemId:'DEMO-ITEM-003'},{status:'reconciling',confirmedAmount:'650.00',items:[{itemId:'DEMO-ITEM-001',status:'confirmed'},{itemId:'DEMO-ITEM-002',status:'confirmed'},{itemId:'DEMO-ITEM-003',status:'broadcast_unknown',amount:'150.00'}],walletObservation:{balance:'350.000000',reservedByThisBatch:'150.000000',unreservedByOne:'200.000000'}},'Alternative branch, not a later state after completion: 650 USDC is confirmed and the last observed wallet balance is 350 USDC. Keep 150 USDC reserved while investigating the third attempt; do not issue another transfer until the original is reconciled. Only definitively failed, unpaid items can receive a new reviewed attempt.')
      ]}
    ]}
  ],
  rules:[
    ['Contract status','Every ONE route, field, status and authentication header in this walkthrough is proposed; provider methods follow the linked documentation and internal handoffs describe responsibilities still to confirm.'],
    ['Response examples','All returned identifiers, amounts and states are fictional example outcomes; provider responses are excerpts or explicitly normalised records, never complete schema definitions.'],
    ['Authorisation','ONE derives merchant scope from authentication and checks resource ownership on every operation; checkout uses an intent-scoped capability, while Dynamic signing uses the active signer’s authenticated session. Headers are illustrative excerpts, so the final specification must preserve ONE’s required authentication and partner authorisation rather than treating the bearer placeholder as a complete scheme.'],
    ['Idempotency','For proposed ONE writes, scope each key to merchant and operation; identical retries return the original result, and a changed payload with the same key returns a conflict.'],
    ['Provider uncertainty','Persist intent and attempt records before external creation or broadcast, then reconcile uncertain outcomes instead of assuming provider idempotency or creating another payment.'],
    ['Money and state','Use decimal strings for displayed amounts and integer base units for transfers, with explicit asset and network identities; source confirmation, crypto receipt and fiat credit remain different states.'],
    ['Provider credentials','Flow server creation uses a server bearer with flow.write, while SDK mutations use the per-flow session token after attachment; never send the server bearer to SDK routes or persist tokens in logs.'],
    ['Provider base URL','Resolve the documented Flow paths against https://app.dynamicauth.com/api/v0, and use the configured environment consistently across creation, source attachment and all later reads.'],
    ['Event handling','If webhooks replace polling, follow the provider’s verified delivery mechanism, deduplicate by environment and event ID, and reconcile current state before changing ONE’s receipt.'],
    ['Signer handoff','Submit creates signing work without signing automatically; specify delivery, integrity checks, chain selection, nonces, rejection handling and broadcast reconciliation before implementing the client handoff.'],
    ['Batch retries','A batch is a collection of independent transactions, so preserve successful items, reconcile unknown broadcasts and create new attempts only for proven unpaid failures.']
  ],
  followups:[
    ['Account services','Confirm where ONE stores the merchant-to-Dynamic binding and how it obtains trusted membership, wallet ownership and signer evidence.'],
    ['Gateway and Flow','Confirm environment access, the intent-scoped checkout capability, provider-event verification, fee presentation and the receipt confirmation policy before fixing these proposed schemas.'],
    ['Payout services','Confirm whether the dashboard batch service can own crypto jobs, then define the signer handoff, reservation owner, nonce handling and eligible retry action.'],
    ['Registry and reconciliation','Confirm how the Wallet service and Core Registry share records, while keeping observed onchain funds separate from ONE custody and fiat balances.']
  ],
  llmBrief:'Use this as a later-stage business-wallet and payout extension to the SPARK Flow-first collection path. Preserve the sequence, identifiers, money units and authority boundaries. Separate documented provider methods from proposed ONE contracts. Define schemas, errors, authentication, idempotency, persistence and state transitions; treat follow-up items as unresolved. Do not make Dynamic Business Accounts a prerequisite for the first Flow checkout, and keep auto-conversion excluded.',
  sources,
  checks:{merchantId,businessAccountId,providerWalletId,walletId,settlementProfileId,intentId,attemptId,flowId,batchId,asset,openingUsdc:'0.000000',receivedUsdc:'1000.000000',payouts:items,closingUsdc:'200.000000'}
};
